version: '3.8'

services:
  postgres:
    image: 'postgres:12.2'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  website:
    depends_on:
      - 'postgres'
    environment:
      - DB_PASSWORD=postgres
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/store'
    volumes_from:
      - box


  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box: